name: 'delivops-github-action-terraform'
description: 'Fully automated Terraform GitHub Action: fmt, init, validate, plan, apply.'
author: 'delivops'
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  working_directory:
    description: 'Directory containing Terraform configuration'
    required: true
  aws_region:
    description: 'AWS Region (e.g., us-east-1, eu-west-1)'
    required: true
  aws_role:
    description: 'AWS Role name to assume for authentication'
    required: true
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.9.8'
  environment:
    description: 'Terraform environment (e.g., dev, staging, prod)'
    required: true
  aws_account_id:
    description: 'AWS Account ID (12-digit number)'
    required: true
  github_token:
    description: 'GitHub token for PR comments'
    required: true
  var_file:
    description: 'Path to a .tfvars file (relative to working_directory)'
    required: false
    default: ''
  extra_args:
    description: 'Additional arguments to pass to terraform plan/apply'
    required: false
    default: ''
  plan_only:
    description: 'Set to true to skip apply even on main branch push'
    required: false
    default: 'false'

outputs:
  fmt_outcome:
    description: 'Outcome of terraform fmt check (success/failure)'
    value: ${{ steps.fmt.outcome }}
  validate_outcome:
    description: 'Outcome of terraform validate (success/failure)'
    value: ${{ steps.validate.outputs.outcome }}
  plan_outcome:
    description: 'Outcome of terraform plan (success/failure/skipped)'
    value: ${{ steps.plan.outcome }}
  apply_outcome:
    description: 'Outcome of terraform apply (success/failure/skipped)'
    value: ${{ steps.apply.outcome }}

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        # Validate AWS Account ID (must be 12 digits)
        if ! [[ "${{ inputs.aws_account_id }}" =~ ^[0-9]{12}$ ]]; then
          echo "::error::Invalid aws_account_id: must be a 12-digit number"
          exit 1
        fi
        
        # Validate AWS Region format (supports standard, gov, and china regions)
        if ! [[ "${{ inputs.aws_region }}" =~ ^[a-z]{2}(-[a-z]+)+-[0-9]+$ ]]; then
          echo "::error::Invalid aws_region format: expected format like 'us-east-1', 'eu-west-2', or 'us-gov-west-1'"
          exit 1
        fi
        
        echo "✅ All inputs validated successfully"

    - name: Git checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role }}"
        aws-region: ${{ inputs.aws_region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      id: fmt
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform fmt -check -diff > "$RUNNER_TEMP/terraform-outputs-fmt.txt" 2>&1 || {
          cat "$RUNNER_TEMP/terraform-outputs-fmt.txt"
          exit 1
        }
      continue-on-error: true

    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if terraform init -no-color > "$RUNNER_TEMP/terraform-outputs-init.txt" 2>&1; then
          cat "$RUNNER_TEMP/terraform-outputs-init.txt"
        else
          echo "--- First attempt failed, trying with -upgrade ---" >> "$RUNNER_TEMP/terraform-outputs-init.txt"
          if terraform init -upgrade -no-color >> "$RUNNER_TEMP/terraform-outputs-init.txt" 2>&1; then
            cat "$RUNNER_TEMP/terraform-outputs-init.txt"
          else
            cat "$RUNNER_TEMP/terraform-outputs-init.txt"
            exit 1
          fi
        fi
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      if: steps.init.outcome == 'success'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if terraform validate -no-color > "$RUNNER_TEMP/terraform-outputs-validate.txt" 2>&1; then
          echo "outcome=success" >> $GITHUB_OUTPUT
        else
          echo "outcome=failure" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: steps.init.outcome == 'success' && github.event_name == 'pull_request' && steps.validate.outputs.outcome == 'success'
      env:
        TF_VAR_FILE: ${{ inputs.var_file }}
        TF_EXTRA_ARGS: ${{ inputs.extra_args }}
      run: |
        VAR_FILE_ARG=""
        if [[ -n "$TF_VAR_FILE" ]]; then
          VAR_FILE_ARG="-var-file=$TF_VAR_FILE"
        fi
        
        # Capture plan output directly so error diagnostics are preserved
        terraform plan -no-color -input=false -out="$RUNNER_TEMP/terraform-outputs-plan.tfplan" $VAR_FILE_ARG $TF_EXTRA_ARGS \
          > "$RUNNER_TEMP/terraform-outputs-plan.txt" 2>&1
        PLAN_EXIT=$?
        if [ $PLAN_EXIT -eq 0 ]; then
          echo "outcome=success" >> $GITHUB_OUTPUT
          # On success, overwrite with terraform show for cleaner formatting
          terraform show -no-color "$RUNNER_TEMP/terraform-outputs-plan.tfplan" > "$RUNNER_TEMP/terraform-outputs-plan.txt" 2>&1 \
            || true
        else
          echo "outcome=failure" >> $GITHUB_OUTPUT
          # On failure, the captured output already contains full error details
        fi
        
        # Extract change counts (e.g., "Plan: 3 to add, 1 to change, 0 to destroy")
        PLAN_SUMMARY=$(grep -E "Plan:|No changes" "$RUNNER_TEMP/terraform-outputs-plan.txt" | head -1 || echo "")
        echo "plan_summary=$PLAN_SUMMARY" >> $GITHUB_OUTPUT
        
        # Detect lock file changes
        if [[ -f ".terraform.lock.hcl" ]]; then
          if git diff --name-only | grep -q ".terraform.lock.hcl"; then
            echo "lock_changed=true" >> $GITHUB_OUTPUT
          else
            echo "lock_changed=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "lock_changed=false" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Comment on PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        VALIDATE_OUTCOME: ${{ steps.validate.outputs.outcome }}
        PLAN_OUTCOME: ${{ steps.plan.outputs.outcome }}
        PLAN_SUMMARY: ${{ steps.plan.outputs.plan_summary }}
        LOCK_CHANGED: ${{ steps.plan.outputs.lock_changed }}
        ENVIRONMENT: ${{ inputs.environment }}
        FMT_OUTCOME: ${{ steps.fmt.outcome }}
        INIT_OUTCOME: ${{ steps.init.outcome }}
        RUNNER_TEMP: ${{ runner.temp }}
        WORKING_DIRECTORY: ${{ inputs.working_directory }}
        TERRAFORM_VERSION: ${{ inputs.terraform_version }}
        GITHUB_WORKFLOW_REF: ${{ github.workflow_ref }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const script = require('${{ github.action_path }}/scripts/pr-comment.js');
          await script({ github, context, core });

    - name: Fail if Any Step Failed
      if: steps.init.outcome == 'failure' || steps.plan.outputs.outcome == 'failure' || steps.validate.outputs.outcome == 'failure'
      shell: bash
      run: exit 1

    - name: Terraform Apply
      id: apply
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' && inputs.plan_only != 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        TF_VAR_FILE: ${{ inputs.var_file }}
        TF_EXTRA_ARGS: ${{ inputs.extra_args }}
      run: |
        VAR_FILE_ARG=""
        if [[ -n "$TF_VAR_FILE" ]]; then
          VAR_FILE_ARG="-var-file=$TF_VAR_FILE"
        fi
        
        terraform apply -auto-approve -input=false $VAR_FILE_ARG $TF_EXTRA_ARGS

    - name: Write Job Summary
      if: always()
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        FMT_OUTCOME: ${{ steps.fmt.outcome }}
        INIT_OUTCOME: ${{ steps.init.outcome }}
        VALIDATE_OUTCOME: ${{ steps.validate.outputs.outcome }}
        PLAN_OUTCOME: ${{ steps.plan.outputs.outcome }}
        PLAN_SUMMARY: ${{ steps.plan.outputs.plan_summary }}
        APPLY_OUTCOME: ${{ steps.apply.outcome }}
      run: |
        # Build status icons
        fmt_icon=$([[ "$FMT_OUTCOME" == "success" ]] && echo "✅" || echo "❌")
        init_icon=$([[ "$INIT_OUTCOME" == "success" ]] && echo "✅" || echo "❌")
        validate_icon=$([[ "$VALIDATE_OUTCOME" == "success" ]] && echo "✅" || echo "❌")
        
        if [[ -z "$PLAN_OUTCOME" ]]; then
          plan_icon="⏭️"
        elif [[ "$PLAN_OUTCOME" == "success" ]]; then
          plan_icon="✅"
        else
          plan_icon="❌"
        fi
        
        if [[ -z "$APPLY_OUTCOME" ]]; then
          apply_icon="⏭️"
        elif [[ "$APPLY_OUTCOME" == "success" ]]; then
          apply_icon="✅"
        else
          apply_icon="❌"
        fi
        
        # Overall status
        if [[ "$INIT_OUTCOME" == "failure" || "$VALIDATE_OUTCOME" == "failure" || "$PLAN_OUTCOME" == "failure" ]]; then
          overall="❌"
        else
          overall="✅"
        fi
        
        # Build summary
        echo "## Terraform $ENVIRONMENT $overall" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Format | $fmt_icon |" >> $GITHUB_STEP_SUMMARY
        echo "| Init | $init_icon |" >> $GITHUB_STEP_SUMMARY
        echo "| Validate | $validate_icon |" >> $GITHUB_STEP_SUMMARY
        echo "| Plan | $plan_icon |" >> $GITHUB_STEP_SUMMARY
        echo "| Apply | $apply_icon |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ -n "$PLAN_SUMMARY" ]]; then
          echo "**$PLAN_SUMMARY**" >> $GITHUB_STEP_SUMMARY
        fi
