name: 'delivops-github-action-terraform'
description: 'Fully automated Terraform GitHub Action: fmt, init, validate, plan, apply.'
author: 'delivops'
branding:
  icon: 'cloud'
  color: 'purple'
inputs:
  working_directory:
    description: 'Directory containing Terraform configuration'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  aws_role:
    description: 'AWS Role to assume for authentication'
    required: true
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.9.8'
  environment:
    description: 'Terraform environment' 
    required: true  
  aws_account_id:
    required: true
  github_token:
    description: 'GitHub token'
    required: true 

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  "arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role }}"
        aws-region: ${{ inputs.aws_region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      id: fmt
      shell: bash
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform init || terraform init -upgrade
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform validate -no-color
      working-directory: ${{ inputs.working_directory }}
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan -no-color -input=false
      working-directory: ${{ inputs.working_directory }}
      if: github.event_name == 'pull_request' && steps.validate.outcome == 'success'
      continue-on-error: true      

    - name: Process Terraform Outputs
      id: process_outputs
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        # Function to truncate and filter terraform output
        process_terraform_output() {
          local input="$1"
          local max_lines=100
          
          if [ -z "$input" ] || [ "$input" = "null" ]; then
            echo "No output available"
            return
          fi
          
          # Create temp file to avoid issues with special characters
          local temp_file=$(mktemp)
          echo "$input" > "$temp_file"
          
          # Find where the actual plan starts
          local filtered_output=""
          local found_start=false
          
          while IFS= read -r line; do
            if [[ "$line" == *"Note: Objects have changed outside of Terraform"* ]] || \
               [[ "$line" == *"Terraform will perform the following actions:"* ]] || \
               [[ "$line" == *"No changes. Your infrastructure matches the configuration."* ]] || \
               [[ "$line" == *"Planning failed. Terraform encountered an error while generating this plan."* ]] || \
               [[ "$line" == *"Plan:"* ]] || \
               [[ "$line" == *"Changes to Outputs:"* ]]; then
              found_start=true
            fi
            
            if [ "$found_start" = true ]; then
              if [ -z "$filtered_output" ]; then
                filtered_output="$line"
              else
                filtered_output="$filtered_output"$'\n'"$line"
              fi
            fi
          done < "$temp_file"
          
          # If no plan start found, use original (but still truncate)
          if [ "$found_start" = false ]; then
            filtered_output="$input"
          fi
          
          # Count lines and truncate if needed
          local line_count
          line_count=$(echo "$filtered_output" | wc -l | tr -d ' ')
          
          if [ "$line_count" -gt "$max_lines" ]; then
            local truncated_count=$((line_count - 50))
            echo "... (${truncated_count} lines truncated) ..."
            echo ""
            echo "$filtered_output" | tail -50
            echo "TRUNCATED=true" >> "$GITHUB_OUTPUT"
          else
            echo "$filtered_output"
          fi
          
          # Cleanup temp file
          rm -f "$temp_file"
        }
        
        # Process validate output
        validate_output=$(process_terraform_output "${{ steps.validate.outputs.stdout }}")
        {
          echo "PROCESSED_VALIDATE_OUTPUT<<EOF"
          echo "$validate_output"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        
        # Process plan output
        plan_output=$(process_terraform_output "${{ steps.plan.outputs.stdout }}")
        {
          echo "PROCESSED_PLAN_OUTPUT<<EOF"
          echo "$plan_output"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        
        # Process plan error
        plan_error=$(process_terraform_output "${{ steps.plan.outputs.stderr }}")
        {
          echo "PROCESSED_PLAN_ERROR<<EOF"
          echo "$plan_error"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
        VALIDATE_OUTPUT: ${{ steps.process_outputs.outputs.PROCESSED_VALIDATE_OUTPUT }}
        PLAN_OUTCOME: ${{ steps.plan.outcome }}
        PLAN_OUTPUT: ${{ steps.process_outputs.outputs.PROCESSED_PLAN_OUTPUT }}
        PLAN_ERROR: ${{ steps.process_outputs.outputs.PROCESSED_PLAN_ERROR }}
        ENVIRONMENT: ${{ inputs.environment }}
        FMT_OUTCOME: ${{ steps.fmt.outcome }}
        INIT_OUTCOME: ${{ steps.init.outcome }}
        HAS_TRUNCATION: ${{ steps.process_outputs.outputs.TRUNCATED }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const environment = process.env.ENVIRONMENT;
          const hasTruncation = process.env.HAS_TRUNCATION === 'true';
          
          // Determine plan section based on outcomes
          let planSection;
          if (process.env.VALIDATE_OUTCOME === 'failure') {
            planSection = "#### Terraform Plan 📖 `skipped` ⏭️\n\n" +
              "<details><summary>Validation Failed - Show Details</summary>\n\n" +
              "```\n" + (process.env.VALIDATE_OUTPUT || 'No validation output') + "\n```\n\n" +
              "</details>\n\n" +
              "> ❌ **Terraform validation failed!** Fix the errors above before merging.";
          } else if (process.env.PLAN_OUTCOME === 'success') {
            planSection = "#### Terraform Plan 📖 `success` ✅\n\n" +
              "<details><summary>Show Plan</summary>\n\n" +
              "```terraform\n" + (process.env.PLAN_OUTPUT || 'No plan output') + "\n```\n\n" +
              "</details>";
          } else if (process.env.PLAN_OUTCOME === 'failure') {
            const errorOutput = process.env.PLAN_ERROR || process.env.PLAN_OUTPUT || 'No error output';
            planSection = "#### Terraform Plan 📖 `failure` ❌\n\n" +
              "<details><summary>Plan Failed - Show Details</summary>\n\n" +
              "```\n" + errorOutput + "\n```\n\n" +
              "</details>\n\n" +
              "> ❌ **Terraform plan failed!** Fix the errors above before merging.";
          } else {
            planSection = "#### Terraform Plan 📖 `skipped` ⏭️\n\n" +
              "> Plan was skipped due to validation failure.";
          }

          // Build complete comment
          const comment = "## Terraform " + environment + "\n" +
            "#### Terraform Format and Style 🖌 `" + process.env.FMT_OUTCOME + "`\n" +
            "#### Terraform Initialization ⚙️ `" + process.env.INIT_OUTCOME + "`\n" +
            "#### Terraform Validation 🤖 `" + process.env.VALIDATE_OUTCOME + "`\n\n" +
            "<details><summary>Validation Output</summary>\n\n" +
            "```\n" + (process.env.VALIDATE_OUTPUT || 'No validation output') + "\n```\n\n" +
            "</details>\n\n" +
            planSection + "\n\n" +
            "*Pushed by: @" + context.actor + ", Action: `" + context.eventName + "`*" +
            (hasTruncation ? "\n\n**⚠️ Output truncated due to length. [View full logs](" + process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + ").**" : "");

          // Find existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const botComment = comments.find(comment => 
            comment.body.includes("## Terraform " + environment)
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              comment_id: botComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
          }

    - name: Fail if Plan Failed
      if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure'
      shell: bash
      run: exit 1

    - name: Terraform Apply
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform apply -auto-approve -input=false
