name: 'delivops-github-action-terraform'
description: 'Fully automated Terraform GitHub Action: fmt, init, validate, plan, apply.'
author: 'delivops'
branding:
  icon: 'cloud'
  color: 'purple'
inputs:
  working_directory:
    description: 'Directory containing Terraform configuration'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  aws_role:
    description: 'AWS Role to assume for authentication'
    required: true
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.9.8'
  environment:
    description: 'Terraform environment' 
    required: true  
  aws_account_id:
    required: true
  github_token:
    description: 'GitHub token'
    required: true 

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  "arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role }}"
        aws-region: ${{ inputs.aws_region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      id: fmt
      shell: bash
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform init || terraform init -upgrade
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform validate -no-color
      working-directory: ${{ inputs.working_directory }}
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan -no-color -input=false
      working-directory: ${{ inputs.working_directory }}
      if: github.event_name == 'pull_request' && steps.validate.outcome == 'success'
      continue-on-error: true      

    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
        PLAN_OUTCOME: ${{ steps.plan.outcome }}
        ENVIRONMENT: ${{ inputs.environment }}
        FMT_OUTCOME: ${{ steps.fmt.outcome }}
        INIT_OUTCOME: ${{ steps.init.outcome }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const environment = process.env.ENVIRONMENT;
          let hasTruncation = false;
          
          // Function to process terraform output
          function processOutput(content) {
            if (!content || content.trim() === '' || content === 'null') {
              return 'No output available';
            }
            
            const lines = content.split('\n');
            
            // Find where the actual plan starts
            const planStartIndicators = [
              'Note: Objects have changed outside of Terraform',
              'Terraform will perform the following actions:',
              'No changes. Your infrastructure matches the configuration.',
              'Planning failed. Terraform encountered an error while generating this plan.',
              'Plan:',
              'Changes to Outputs:'
            ];
            
            let planStartIndex = -1;
            for (let i = 0; i < lines.length; i++) {
              if (planStartIndicators.some(indicator => lines[i].includes(indicator))) {
                planStartIndex = i;
                break;
              }
            }
            
            // Use filtered lines from plan start, or all lines if no plan start found
            const relevantLines = planStartIndex >= 0 ? lines.slice(planStartIndex) : lines;
            
            // Truncate if too long
            if (relevantLines.length > 100) {
              hasTruncation = true;
              const truncatedLines = relevantLines.slice(-50);
              return `... (${relevantLines.length - 50} lines truncated) ...\n\n${truncatedLines.join('\n')}`;
            }
            
            return relevantLines.join('\n');
          }
          
          // Get and process outputs directly from step outputs
          const validateOutput = processOutput(`${{ steps.validate.outputs.stdout }}`);
          const planOutput = processOutput(`${{ steps.plan.outputs.stdout }}`);
          const errorOutput = processOutput(`${{ steps.plan.outputs.stderr }}`);

          // Determine plan section based on outcomes
          let planSection;
          if (process.env.VALIDATE_OUTCOME === 'failure') {
            planSection = "#### Terraform Plan 📖 `skipped` ⏭️\n\n" +
              "<details><summary>Validation Failed - Show Details</summary>\n\n" +
              "```\n" + validateOutput + "\n```\n\n" +
              "</details>\n\n" +
              "> ❌ **Terraform validation failed!** Fix the errors above before merging.";
          } else if (process.env.PLAN_OUTCOME === 'success') {
            planSection = "#### Terraform Plan 📖 `success` ✅\n\n" +
              "<details><summary>Show Plan</summary>\n\n" +
              "```terraform\n" + planOutput + "\n```\n\n" +
              "</details>";
          } else if (process.env.PLAN_OUTCOME === 'failure') {
            const finalErrorOutput = errorOutput !== 'No output available' ? errorOutput : planOutput;
            planSection = "#### Terraform Plan 📖 `failure` ❌\n\n" +
              "<details><summary>Plan Failed - Show Details</summary>\n\n" +
              "```\n" + finalErrorOutput + "\n```\n\n" +
              "</details>\n\n" +
              "> ❌ **Terraform plan failed!** Fix the errors above before merging.";
          } else {
            planSection = "#### Terraform Plan 📖 `skipped` ⏭️\n\n" +
              "> Plan was skipped due to validation failure.";
          }

          // Build complete comment
          const comment = "## Terraform " + environment + "\n" +
            "#### Terraform Format and Style 🖌 `" + process.env.FMT_OUTCOME + "`\n" +
            "#### Terraform Initialization ⚙️ `" + process.env.INIT_OUTCOME + "`\n" +
            "#### Terraform Validation 🤖 `" + process.env.VALIDATE_OUTCOME + "`\n\n" +
            "<details><summary>Validation Output</summary>\n\n" +
            "```\n" + validateOutput + "\n```\n\n" +
            "</details>\n\n" +
            planSection + "\n\n" +
            "*Pushed by: @" + context.actor + ", Action: `" + context.eventName + "`*" +
            (hasTruncation ? "\n\n**⚠️ Output truncated due to length. [View full logs](" + process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + ").**" : "");

          // Find existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const botComment = comments.find(comment => 
            comment.body.includes("## Terraform " + environment)
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              comment_id: botComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
          }

    - name: Fail if Plan Failed
      if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure'
      shell: bash
      run: exit 1

    - name: Terraform Apply
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform apply -auto-approve -input=false
